# Site settings
title: jybaek.github.io 
home: http://jybaek.github.io
stackoverflow: http://stackoverflow.com/users/4599185/baek-jae-yeon
email: oops.jybaek@gmail.com 
admin: Baek Jae-Yeon
description: "Copyright(c)2016 Baek,Jae-Yeon All rights reserved"
baseurl: ""
url: "https://jybaek.github.io"
github_username:  jybaek
facebook_username: WeGuardia
stackoverflow_username: 4599185
google_analytics_id: UA-80265650-1

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes"]

highlighter: pygments

permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji
